---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cce-data
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /cce/data
    server: {{ nfs_domain_name }} # todo determine how to use env vars
