---
kind: Service
apiVersion: v1
metadata:
  name: cce-front-end-service-dev
  labels:
    app: cce-dev
    phase: dev
    tier: service
    deployment: v0
spec:
  selector:
    app: cce-front-end-dev
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetport: 80
