version: "3.7"

# Reference: https://docs.docker.com/compose/compose-file/

networks:
  ccenet:
    driver: bridge

services:

  ccedb:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${CCE_DB_USERNAME}
      POSTGRES_PASSWORD: ${CCE_DB_PASSWORD}
      PGDATA: ${CCE_DATA_DIR}
      POSTGRES_DB: ${CCE_DB_NAME}
    volumes:
      - "cce_dbdata:${CCE_DATA_DIR}"
    networks:
      - ccenet
    ports:
      - "5432:5432/tcp"

  cceredis:
    build:
      context: .
      dockerfile: cce-redis.dockerfile
      labels:
        - "env=dev"
    networks:
      - ccenet
    volumes:
      - "cce_redis:/data"
    ports:
      - "6379:6379"
    environment:
      REDIS_PORT: ${CCE_REDIS_PORT}
      REDIS_PWD: ${CCE_REDIS_PASSWORD}
      REDIS_DB_NUMBER: ${CCE_REDIS_DB_NUMBER}
      REDIS_BIND_INTERFACE: ${CCE_REDIS_BIND_INTERFACE}
      REDIS_MAX_CLIENTS: ${CCE_REDIS_MAX_CLIENTS}

  cceapp:
    build:
      args:
        APP_REPO: ${CCE_APP_REPO}
      context: .
      dockerfile: cce-api.dockerfile
    environment:
      DB_HOST: ${CCE_DB_HOST}
      DB_NAME: ${CCE_DB_NAME}
      DB_PORT: ${CCE_DB_PORT}
      DB_USERNAME: ${CCE_DB_USERNAME}
      DB_PASSWORD: ${CCE_DB_PASSWORD}
      DB_SSL_MODE: ${CCE_DB_SSL_MODE}  # disable
    ports:
      - "8080:8080/tcp"
    networks:
      - ccenet

volumes:
  cce_dbdata:
  cce_redis:



