version: "3.1"

services:

  cce-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${CCE_DB_USERNAME}
      POSTGRES_PASSWORD: ${CCE_DB_PASSWORD}
      PGDATA: ${CCE_DATA_DIR}
      POSTGRES_DB: ${CCE_DB_NAME}
    volumes:
      - "cce_dbdata:${CCE_DATA_DIR}"

  cce-app:
    build:
      args:
        APP_REPO: ${CCE_APP_REPO}
      context: .
      dockerfile: cce-api.dockerfile
    environment:
      DB_URL: ${CCE_DB_URL}
      DB_PORT: ${CCE_DB_PORT}
      DB_USERNAME: ${CCE_DB_USERNAME}
      DB_PASSWORD: ${CCE_DB_PASSWORD}
    ports:
      - "8080:80/tcp"

volumes:
  cce_dbdata:


