version: '3.1'

services:

  cce-db:
    build:
      context: .
      dockerfile: cce-db.dockerfile
      args:
        - POSTGRES_PASSWORD
        - POSTGRES_USER
        - PGDATA
        - POSTGRES_DB
        - POSTGRES_INITDB_WALDIR
      labels:
        cce.app.description: "CCE PostgreSQL database back-end"
        cce.app.phase: "dev"
        cce.app.version: "v0.0"
    restart: always

  cce-app:
    build:
      context: .
      dockerfile: cce-api.dockerfile
      args:
        - DATABASE_URL
        - DATABASE_PORT
        - DATABASE_USERNAME
        - DATABASE_PASSWORD
      labels:
        cce.app.description: "CCE Go API front-end"
        cce.app.phase: "dev"
        ccc.app.version: "v0.0"
    restart: always
    environment:
      DB_URL: ${CCE_DB_URL}
      DB_USERNAME: ${CCE_DB_USERNAME}
      DB_PASSWORD: ${CCE_DB_PASSWORD}
      DB_PORT: ${CCE_DB_PORT}
